name: Android CI

on:
  push:
    branches: [ "development" ]
jobs:
#   test:
#     name: Run Unit Tests
#     runs-on: ubuntu-latest

#     steps:
#     - uses: actions/checkout@v3
#     - name: set up JDK 11
#       uses: actions/setup-java@v3
#       with:
#         java-version: '11'
#         distribution: 'temurin'
#         cache: gradle
#     - name: Unit tests
#       run: bash ./gradlew test --stacktrace

  build:
    name: Generate APK
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
  
    # - name: Perform Scan
    #   uses: ShiftLeftSecurity/scan-action@master
  
    - name: set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: gradle

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build with Gradle
      run: ./gradlew assembleRelease
    - name: Upload APK
      uses: actions/upload-artifact@v1
      with:
        name: app
        path: app/build/outputs/apk/release/app-release-unsigned.apk

    - name: Github Tag Bump
      id: tag_bump
      uses: anothrNick/github-tag-action@1.39.0
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        DEFAULT_BUMP: patch

    - name: Create a Release
      uses: "marvinpinto/action-automatic-releases@latest"
      with:
        repo_token: "${{ secrets.GITHUB_TOKEN }}"
        automatic_release_tag: ${{ steps.tag_bump.outputs.new_tag}}
        prerelease: true
        files: |
          app/build/outputs/apk/*/*.apk